source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'JHLocationService_Example' do
  #pod 'JHUIKit', :git => 'https://github.com/seraphjiang/JHUIKit.git'
  pod 'JHLocationService', :path => '../'

  target 'JHLocationService_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase', :git => 'https://github.com/facebook/ios-snapshot-test-case.git', :commit => 'b898c25'
  pod 'Nimble-Snapshots'
  
  end
end
