use_frameworks!

target 'JHLocationService_Example' do
  pod 'JHLocationService', :path => '../'

  target 'JHLocationService_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
